# Generated by Django 6.0.4 on 2026-06-29 12:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_otpverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='producelisting',
            name='status',
            field=models.CharField(choices=[('Listed', 'Listed'), ('Matched', 'Matched'), ('Processing', 'Processing')], default='Listed', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Order received', 'Order received'), ('Assigned', 'Assigned'), ('Processing', 'Processing'), ('Completed', 'Completed')], default='Order received', max_length=20),
        ),
        migrations.CreateModel(
            name='HubInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=12)),
                ('location', models.CharField(max_length=255)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('hub', models.ForeignKey(limit_choices_to={'role': 'HUB'}, on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
